using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Note : MonoBehaviour
{
    public float noteSpeed = 800;

    UnityEngine.UI.Image noteImage;

    void OnEnable()
    {
        if (noteImage == null)
            noteImage = GetComponent<UnityEngine.UI.Image>();

        noteImage.enabled = true;
    }

    public void HideNote()
    {
        noteImage.enabled = false;
    }

    public bool GetNoteFlag()
    {
        return noteImage.enabled;
    }

    // Update is called once per frame
    void Update()
    {
        transform.localPosition -= Vector3.right * noteSpeed * Time.deltaTime;
    }
}
